CREATE TABLE IF NOT EXISTS user_norm_fulfilments (
    id SERIAL PRIMARY KEY,
    user_profile_id INTEGER NOT NULL,
    topic TEXT NOT NULL,
    title TEXT NOT NULL,
    number_of_norm_decrease INTEGER NOT NULL,
    number_of_items INTEGER NOT NULL,
    number_of_items_solved INTEGER NOT NULL,
    evaluation_id INTEGER,
    date_of_evaluation DATE,
    date_of_evaluation_validity DATE,
    norm_start_date DATE NOT NULL,
    norm_end_date DATE NOT NULL,
    relocation_id INTEGER,
    file_id INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_profile_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
    FOREIGN KEY (evaluation_id) REFERENCES evaluations(id) ON DELETE CASCADE,
    FOREIGN KEY (relocation_id) REFERENCES employee_absents(id) ON DELETE CASCADE
);
