CREATE TABLE IF NOT EXISTS revisions_of_organization_units (
    id serial PRIMARY KEY,
    revision_type_id INT NOT NULL,
    revisor_user_profile_id INT,
    revisor_user_profile TEXT,
    internal_organization_unit_id INT,
    external_organization_unit_id INT,
    responsible_user_profile_id INT,
    responsible_user_profile TEXT,
    implementation_user_profile_id INT,
    implementation_user_profile TEXT,
    title TEXT NOT NULL,
    planned_year TEXT NOT NULL,
    planned_quarter TEXT NOT NULL,
    serial_number TEXT,
    priority TEXT,
    date_of_revision DATE,
    date_of_acceptance DATE,
    date_of_rejection DATE,
    implementation_suggestion TEXT,
    implementation_month_span TEXT,
    date_of_implementation DATE,
    state_of_implementation TEXT,
    implementation_failed_description TEXT,
    second_implementation_month_span TEXT,
    second_date_of_revision DATE,
    file_id INT,
    ref_document TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (implementation_user_profile_id) REFERENCES user_profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (revisor_user_profile_id) REFERENCES user_profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (responsible_user_profile_id) REFERENCES user_profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (internal_organization_unit_id) REFERENCES organization_units (id) ON UPDATE CASCADE ON DELETE CASCADE
);
