CREATE TABLE IF NOT EXISTS employee_family_members (
    id serial PRIMARY KEY,
    user_profile_id INT NOT NULL,
    first_name text NOT NULL,
    middle_name text,
    last_name text NOT NULL,
    birth_last_name text,
    father_name text NOT NULL,
    mother_name text NOT NULL,
    mother_birth_last_name text NOT NULL,
    date_of_birth date NOT NULL,
    country_of_birth text NOT NULL,
    city_of_birth text NOT NULL,
    nationality text NOT NULL,
    citizenship text NOT NULL,
    address text NOT NULL,
    official_personal_id text NOT NULL,
    gender text NOT NULL,
    employee_relationship text NOT NULL,
    insurance_coverage text NOT NULL,
    handicapped_person boolean NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);